### PR TITLE
Move ts-specific overlay to dev module for use in the hydra

### PR DESCRIPTION
**Pull request by countvajhula**
### Summary of Changes

There was still some leftover overlay code in the ts module which was being used by the hydra used for development. I've moved that over to the dev module.

### Public Domain Dedication

- [x] In contributing, I relinquish any copyright claims on my contribution and freely release it into the public domain in the simple hope that it will provide value.

### CODE REVIEW

**Comment by polaris64** [comment]
@countvajhula, I know you requested my review on this PR so I'm just letting you know that I made a comment above (just in case you missed it) :)

**Comment by countvajhula** [comment]
@polaris64 hmm I still don't see any comments besides your most recent one. Are you sure you mean the present PR and not a different one?

**Comment by polaris64** [comment]
@countvajhula that's strange, I can see it but perhaps I accidentally made it invisible to you (I'm not too familiar with reviewing code on GitHub).

Screenshot_20220830-193737

Above is how it appears to me (on my phone at the moment).

**Comment by countvajhula** [comment]
Re: your comment, now that I'm looking at it, I think I might have removed `symex-ts--current-node` by mistake assuming that it was `symex-ts--current-overlay` (which was already removed in the "generalize overlay" PR)! I'll add it back, and sounds like `defvar-local` is the right choice here so I'll make that change as well.

**Comment by countvajhula** [comment]
@polaris64 Oh, weird. My guess is you might have accidentally "started a review" in the GitHub UI, and then the comment doesn't go through unless you click "Finish review". Your other comment "I know you requested ..." was posted as a regular comment instead of as part of a review so it came through immediately.

**Comment by countvajhula** [comment]
Re: your comment, now that I'm looking at it, I think I might have removed `symex-ts--current-node` by mistake assuming that it was `symex-ts--current-overlay` (which was already removed in the "generalize overlay" PR)! I'll add it back, and sounds like `defvar-local` is the right choice here so I'll make that change as well.

**Comment by polaris64** [comment]
> @polaris64 Oh, weird. My guess is you might have accidentally "started a review" in the GitHub UI, and then the comment doesn't go through unless you click "Finish review".

Ah OK, that explains it, yes that's what I did. Sorry for the confusion!

**Review by polaris64 — APPROVED** [review]
I haven't tested it as I don't have access to my computer at the moment but based on the diffs it looks fine

**Pull request merged**
