### PR TITLE
Add symex--special-left-p case for Clojure(script) deref reader macro

### PR DESCRIPTION
**Pull request by dcostaras**
### Summary of Changes

Hi,

I've been really enjoying symex and would like to contribute. This is a rather small PR just to get the process ironed out. One question; there don't seem to be any tests besides the manual ones in the dev-utils file, do you have tests?

This PR adds a symex--special-left-p case for Clojure(script) deref reader macro.

### Public Domain Dedication

- [x] In contributing, I relinquish any copyright claims on my contribution and freely release it into the public domain in the simple hope that it will provide value.

(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on attribution -- where those who give more are more empowered -- is significantly more efficient than capitalism while also being stable and fair (_unlike_ capitalism, on both counts), giving it transformative power to elevate the human condition and address the problems that face us today along with a host of others that have been intractable since the beginning. You can help make this a reality by releasing your work in the same way -- freely into the public domain in the simple hope of providing value. Learn more about attribution-based economics at [drym.org](https://drym.org), tell your friends, do your part.)

### CODE REVIEW

**Comment by countvajhula** [comment]
Welcome, and thank you for your contribution @dcostaras . There are no tests 😆 
In theory I'd love to add some, but in practice it hasn't caused too many issues and so it hasn't become a priority. I would certainly accept PRs with tests, and it could lay the groundwork for more tests over time. But for now, I'm equally happy to accept PRs without tests.

**Comment by dcostaras** [comment]
Ok, this is the first time I've contributed to an Emacs package so was just making sure I wasn't missing anything. 

There is one build failure `212:0: error: "deftraversal" doesn't start with package's prefix "symex".` unrelated to the PR. Is this something you've encountered before?

**Comment by dcostaras** [comment]
I see the other open PR is having the same issue...

**Comment by countvajhula** [comment]
@dcostaras Yeah don't worry about that `deftraversal` issue. I've just renamed that macro on the master branch so that error shouldn't appear in future pull requests (or this one, if you rebased your branch).

**Comment by countvajhula** [comment]
Appreciate the docstring fixes 😄 
Do you have any examples of the deref reader macro that I could look at?

**Pull request closed without merging**
